/* https://school.programmers.co.kr/learn/courses/30/lessons/131117 */

SELECT PD.PRODUCT_ID, PD.PRODUCT_NAME, SUM(PD.PRICE * OD.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT PD JOIN FOOD_ORDER OD ON PD.PRODUCT_ID = OD.PRODUCT_ID
WHERE OD.PRODUCE_DATE LIKE '2022-05%'
GROUP BY PD.PRODUCT_ID
ORDER BY 3 DESC, 1
