/* https://school.programmers.co.kr/learn/courses/30/lessons/133025 */

SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF LEFT JOIN ICECREAM_INFO
ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE FIRST_HALF.TOTAL_ORDER > 3000 AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC



/* 별칭을 사용한 다른 풀이 */
SELECT a.FLAVOR
FROM FIRST_HALF AS a
LEFT JOIN ICECREAM_INFO AS b
ON a.FLAVOR = b.FLAVOR  /* a의 기본키와 b의 기본키(외래키) 연결 */
WHERE a.TOTAL_ORDER > 3000 AND b.INGREDIENT_TYPE = 'fruit_based'
ORDER BY a.TOTAL_ORDER DESC
