/* https://school.programmers.co.kr/learn/courses/30/lessons/131124 */

WITH CNT_REVIEW AS (SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE, COUNT(*) CNT
      FROM REST_REVIEW
      GROUP BY MEMBER_ID)

SELECT MEMBER_NAME, rest.REVIEW_TEXT, DATE_FORMAT(rest.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW rest 
    JOIN CNT_REVIEW cnt ON rest.MEMBER_ID = cnt.MEMBER_ID 
    JOIN MEMBER_PROFILE mem ON rest.MEMBER_ID = mem.MEMBER_ID
WHERE CNT = (SELECT MAX(CNT) FROM CNT_REVIEW)
ORDER BY 3, 2
