/* https://school.programmers.co.kr/learn/courses/30/lessons/133026 */

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF T1 JOIN ICECREAM_INFO T2 ON T1.FLAVOR = T2.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY 2
