/* https://school.programmers.co.kr/learn/courses/30/lessons/273711 */

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT T2.ITEM_ID
    FROM ITEM_INFO T1 JOIN ITEM_TREE T2 ON T2.PARENT_ITEM_ID = T1.ITEM_ID
    WHERE T1.RARITY = 'RARE'
    )
ORDER BY 1 DESC
