/* https://school.programmers.co.kr/learn/courses/30/lessons/144856 */

SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM BOOK A JOIN AUTHOR B JOIN BOOK_SALES C
ON A.AUTHOR_ID = B.AUTHOR_ID AND A.BOOK_ID = C.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY A.CATEGORY, A.AUTHOR_ID
ORDER BY 1, 3 DESC
