/* https://school.programmers.co.kr/learn/courses/30/lessons/276034 */

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME='Python') OR
    SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME='C#')
ORDER BY ID


-- 비트 연산자가 바로바로 생각이 안남..
