/* https://school.programmers.co.kr/learn/courses/30/lessons/164671 */


SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/', B.FILE_ID, B.FILE_NAME, B.FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD A LEFT JOIN USED_GOODS_FILE B ON A.BOARD_ID = B.BOARD_ID
WHERE A.VIEWS = (SELECT MAX(ugb.VIEWS) FROM USED_GOODS_BOARD ugb)
ORDER BY A.BOARD_ID
